service: ${env:APP_SERVICE_NAME}
variablesResolutionMode: 20210219
useDotenv: true

plugins:
  - serverless-offline
  - serverless-plugin-typescript
  - serverless-plugin-optimize
  - serverless-pseudo-parameters

provider:
  name: aws
  runtime: nodejs12.x
  region: ${env:AWS_REGION}
  stage: ${opt:stage,'dev'}
  lambdaHashingVersion: 20201221
  apiGateway:
    shouldStartNameWithService: true

functions:
  add:
    handler: src/add/add.handler
    events:
      - http:
          path: add
          method: post
          cors: true
