version: 0.2

phases:
  install:
    commands:
      - cd server
      - npm install --silent --no-progress -g npm
  pre_build:
    commands:
      - npm install --silent --no-progress
  build:
    commands:
      - npm run sls:package -- --stage $APP_STAGE -r $AWS_REGION
  post_build:
    commands:
      - npm run sls:deploy -- --stage $APP_STAGE -r $AWS_REGION
